#!/bin/sh
cd /
mkdir repos
cd repos
git clone https://github.com/periish/kiss-all
git clone https://github.com/kisslinux/repo
git clone https://github.com/kisslinux/community
rm -rf community/community/libsndfile
mkdir lin-kern
export KISS_PATH=''
KISS_PATH=$KISS_PATH:/repos/community/community
KISS_PATH=$KISS_PATH:/repos/repo/core
KISS_PATH=$KISS_PATH:/repos/repo/testing
KISS_PATH=$KISS_PATH:/repos/repo/xorg
KISS_PATH=$KISS_PATH:/repos/repo/extra
KISS_PATH=$KISS_PATH:/repos/kiss-all/audio
KISS_PATH=$KISS_PATH:/repos/kiss-all/cmd-utils
KISS_PATH=$KISS_PATH:/repos/kiss-all/containers
KISS_PATH=$KISS_PATH:/repos/kiss-all/dbus
KISS_PATH=$KISS_PATH:/repos/kiss-all/dbus
KISS_PATH=$KISS_PATH:/repos/kiss-all/misc
KISS_PATH=$KISS_PATH:/repos/kiss-all/ricing
KISS_PATH=$KISS_PATH:/repos/kiss-all/xfce4
export CFLAGS="-O2 -march=native -pipe"
export CXXFLAGS="$CFLAGS"
export MAKEFLAGS="-j2"
kiss b gnupg1
kiss i gnupg1
gpg --keyserver keys.gnupg.net --recv-key 46D62DD9F1DE636E
echo trusted-key 0x46d62dd9f1de636e >>/root/.gnupg/gpg.conf
cd /var/db/kiss/repo
git config merge.verifySignatures true
kiss update
cd /var/db/kiss/installed && kiss build *
kiss b e2fsprogs dosfstools xfsprogs util-linux eudev wpa_supplicant dhcpcd nano libelf ncurses perl
kiss i e2fsprogs dosfstools xfsprogs util-linux eudev wpa_supplicant dhcpcd nano libelf ncurses perl
echo HOSTNAME > /etc/hostname
nano /etc/hosts
cd /repos/lin-kern
wget https://git.kernel.org/torvalds/t/linux-5.10-rc3.tar.gz
tar -xf linux-5.10-rc3.tar.gz
rm linux-5.10-rc3.tar.gz
cd linux-5.10-rc3
make defconfig
make menuconfig
cp .config /repos
make -j2
kiss b grub efibootmgr
kiss i grub efibootmgr
make install
mv /boot/vmlinuz /boot/vmlinuz-5.10-rc3
mv /boot/System.map /boot/System.map-5.10-rc3
cd /repos/lin-kern
wget https://raw.githubusercontent.com/Arturo211234/void-basic-setup/master/genfstab
chmod +x genfstab
./genfstab -U / >> /etc/fstab
grub-install --target=x86_64-efi --efi-directory=/dev/sda1 --bootloader-id=kiss
grub-mkconfig -o /boot/grub/grub.cfg
kiss b baseinit
kiss i baseinit
adduser aslikr
kiss b xorg-server xinit xf86-input-libinput liberation-fonts dwm dmenu pulseaudio
addgroup aslikr video
addgroup aslikr audio
cd /repos
mkdir myrepo
cd myrepo
wget https://dl.suckless.org/st/st-0.8.4.tar.gz
tar -xf st-0.8.4.tar.gz
rm st-0.8.4.tar.gz
cd st-0.8.4
mv config.def.h config.h
make -j2
